# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: example_app
  pool: 5
  username: user
  password: password

staging:
  <<: *default
  database: example_app
  pool: 25
  username: someuser
  password: somepassword

production:
  <<: *default
  database: example_app
  pool: 50
  username: someuser
  password: somepassword
